name: CI

on:
  push:
    branches: [main]
    
  schedule:
    - cron: "* */5 * * 1,3,5"
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Replace with the desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python run_tests.py  # Replace with the command to run your tests
